### ISSUE TITLE
Tab Bar Controller with WebView  problem

### ISSUE THREAD

**Issue by wenjonsommers** [rshankras/Swift-Demo#1]
Having an issue with the Tab Bar Controller with WebView tutorial. Thanks for the tutorial by the way. Helped a lot.

But, I noticed after I open up another page via a link in the webview, for example any of the menu items that show up in the CNN menu, and then try to press the "World" tab bar item, nothing happens...? Is that the expected behavior, or...?

**Comment by rshankras** [comment]
That is the expected behaviour, you will have to switch to the other tab and come back again. If browser support is enabled then we can show the home page agian.

May be this project might help you - WebViewDemo under Swift-Demo
Thanks
